### ISSUE TITLE
Place module script in the head

### ISSUE THREAD

**Issue by follywolly** [Denniswegereef/web-app-from-scratch-18-19#1]
According to [JoostF](https://github.com/joostf), module scripts defer automatically, so the sooner it starts loading the better.

https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/e5791c01316ef9446663c8f592654415e34e9f0c/src/index.html#L28

**Comment by Denniswegereef** [comment]
Omg, didn't know it. Any article to back it up?

**Comment by follywolly** [comment]
Yes, there's a great [article by google](https://developers.google.com/web/fundamentals/primers/modules#defer) about module scripts! 
I've linked it to the part about auto defer.

**Comment by Denniswegereef** [comment]
Alright! Fixed it thanks
