### ISSUE TITLE
Use the hashchange event to listen to route changes instead of hacking the click event

### ISSUE THREAD

**Issue by follywolly** [Denniswegereef/web-app-from-scratch-18-19#2]
You can use `window.addEventListener('hashchange', ()=>{ some action }) ` to listen to the link hash changing. You don't need to worry about the preventDefault since hash links will not trigger a page load.
It means your functionality will still work, but link tags are still working like they used to, which can prevent issues later on.
I'd do it like this:
```js
window.addEventListener('hashchange', () => {
  const goLink = window.location.href.split('#')[1] // or whatever you need to get the route name
  history.replaceState(null, '', router.options.baseUrl + goLink) 
  router.changeRoute(goLink)
})
```

https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/e5791c01316ef9446663c8f592654415e34e9f0c/src/js/router.js#L57-L68

**Comment by Denniswegereef** [comment]
Rewrote my router, now working with hashchanges!
