### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by maanlamp** [Denniswegereef/web-app-from-scratch-18-19#3]
https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/e5791c01316ef9446663c8f592654415e34e9f0c/src/js/index.js#L10

https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/e5791c01316ef9446663c8f592654415e34e9f0c/src/js/index.js#L13

**Comment by Denniswegereef** [comment]
Removed it
