### ISSUE TITLE
Don't use normal function, use arrow function

### ISSUE THREAD

**Issue by maanlamp** [Denniswegereef/web-app-from-scratch-18-19#4]
https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/e5791c01316ef9446663c8f592654415e34e9f0c/src/js/router.js#L58-L67

You are using arrow functions everywhere else, why not here?

You don't have to use `this`, in fact: it's bad practise. Use an arrow function to avoid unnecessary this binding, and use the variable `a` or `e.srcElement` instead.

**Comment by Denniswegereef** [comment]
Removed this part of code
