### ISSUE TITLE
Unnecessary 404 header status checking 

### ISSUE THREAD

**Issue by follywolly** [Denniswegereef/web-app-from-scratch-18-19#9]
Can be removed since you return res.json() anyway

https://github.com/Denniswegereef/web-app-from-scratch-18-19/blob/be9562fe88baa13f13ad1e55ce62425d9b4e0f3c/src/js/helper/api.js#L30-L32

**Comment by Denniswegereef** [comment]
Thank you for your awareness, fixed it!
